### ISSUE TITLE
Show value and culprit in exceptions

### ISSUE THREAD

**Issue by UkeHa** [ChrisHodges/ExcelToEnumerable#5] opened 2020-11-02 10:25 UTC
While trying to import massive amounts of data from excel, some values might not fit into the schema. Instead of relying on a list with the parameter ".OutputExceptionsTo()" it would be nice to see the value that led to the exception as well as the row in excel the exception was thrown from. So instead of 
```
"Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Double.Parse(String s, IFormatProvider provider)"
```
```
"Unhandled exception. System.FormatException: Input string (value: "0´.00") was not in a correct format (offending row: "current_balance").
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Double.Parse(String s, IFormatProvider provider)"
```

**Comment by ChrisHodges** [comment] 2020-11-02 10:55
If the reader encounters a parsing Exception for a given cell, it will wrap it in an exception of type `ExcelToEnumerableCellException` which has the following properties:

`Column` - the column letter of the cell that caused the exception.
`RowNumber` - the 1-based row number of the cell that caused the exception.
`PropertyName` - the name of the property that ExcelToEnumerable was attempting to map.

Does this functionality cover your use case?

**Comment by UkeHa** [comment] 2020-11-02 11:03
Sure, that way you can at least find the failing value yourself and perhaps fix the issue! Is that information only put out in the aforementioned outputexceptionto-list or did i simply miss that info in the stacktrace? If the former is the case, would it be able to also add that info in the "normal" exception message?

**Comment by ChrisHodges** [comment] 2020-11-02 11:15
An `ExcelToEnumerableCellException` will have a message like:

> "Unable to set value 'Cell value' to property 'double' on row 2 column A. Value is invalid"

...and its inner exception will be the wrapped exception encountered by the reader. It shouldn't matter whether the exceptions are being thrown immediately, or aggregated, or output to an exception list. 

You should be seeing message similar to the one above in your stack trace, but you'll have to catch or cast the ExcelToEnumerableCellException to access the Column, RowNumber and PropertyName properties.

**Comment by UkeHa** [comment] 2020-11-02 11:27
The problem is, that i don't encounter an ExcelToEnumerableCellException but get a System.FormatException, even though my target type is string. For whatever reason the lib thinks it must parse the number as a double (perhaps because the field is handled as "default" in excel?) and dies as it tries to parse a number that is too big for double. If i try to add the error to a list, the import fails too and i get nothing in the exception list.

**Comment by ChrisHodges** [comment] 2020-11-02 11:30
That sounds strange. Are you able to post or email me some reproducible code so I can see what's happening?

**Comment by UkeHa** [comment] 2020-11-02 11:41
That's kinda hard for me to do, but i'll see what i can do:

Here's a string value that i try to parse (marked as standard in excel an shown as 7+e15) "7060151014090010" and while importing a couple of thousand rows it seems to be the problem. But that is hard to narrow down, as i get no indication as to which field throws the error and i've got multiple hundred thousand datarows + columns from A to AAO or something. We removed a bunch of data that wasn't necessary at the moment and the import worked. I'll try to re-add it, to find out if that was the problem.

EDIT: After adding the row back in, the import works. @ChrisHodges have you ever tried to import huge excel files? Is there a known upper limit?

**Comment by ChrisHodges** [comment] 2020-11-02 11:45
Are you able to post a stack trace?

**Comment by ChrisHodges** [comment] 2020-11-02 12:02
@UkeHa yes the ability to import large spreadsheets was the original motivation for the project. I've been able to import 100,000+ rows successfully. I'm not sure what the practical upper row limit is but I expect it will be dictated by the CPU and memory rather than a specific constraint on one of the components of the software.

Let me know if you are able to post a stack trace. This feels like it may be a bug, as I would always expect a FormatException to be wrapped in an ExcelToEnumerable exception.

**Comment by ChrisHodges** [comment] 2020-11-09 10:52
@UkeHa I've been unable to reproduce the bug you described in the op so I'm intending to close this issue. I've added a test that reads 1 million items of data to the test project [here](https://github.com/ChrisHodges/ExcelToEnumerable/commit/198c43b19684e015cbc6b4f887733e808a320c48) so I'm confident that the library can handle large volumes of data. I suspect the problem you describe may be caused by the XML in the specific spreadsheet you're using. Please raise another issue with a reproducible example if you are able.

**Closed as completed by ChrisHodges** 2020-11-09 10:52 UTC
